# Generated by Django 3.2.16 on 2025-12-26 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_location_is_published'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='is_published',
        ),
    ]
