# Generated by Django 3.2.16 on 2025-12-26 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_category_is_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
    ]
